name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # composer.json がある場合のみ有効化する
      # - name: composer install
      #   run: composer install

      - name: get tag name
        id: tag
        run: echo "tagname=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: add version
        run: sed -i -e "s/{release version}/${{ steps.tag.outputs.tagname }}/g" style.css

      - name: create archive
        env:
          PACKAGE_NAME: "shifter-github-hosting-theme-sample"
          FILES_TO_ARCHIVE: "*.php *.md *.css *.txt *.png LICENSE phpcs.xml.dist inc/ js/ languages/ layouts/ template-parts/"
        run: zip -r ${PACKAGE_NAME}.zip ${FILES_TO_ARCHIVE}

      - name: upload to github release
        uses: softprops/action-gh-release@v2
        env:
          PACKAGE_NAME: "shifter-github-hosting-theme-sample"
        with:
          tag_name: ${{ steps.tag.outputs.tagname }}
          name: "${{ env.PACKAGE_NAME }} ${{ steps.tag.outputs.tagname }}"
          files: ${{ env.PACKAGE_NAME }}.zip
